### PR TITLE
Add 3.7 dev to the travis config

### PR DESCRIPTION
**Pull request by d0ugal**

### CODE REVIEW

**Comment by tomchristie** [comment]
Thanks! Can't quite see what the diff in the failure is at a glance.
Might be a different dictionary ordering?

**Comment by d0ugal** [comment]
I believe this is in the expected schema, but isn't in the response.text. Why? I have no idea.

```
E         -          ]
E         +          ],
E         ?           +
E         +                 "responses": {
E         +                     "200": {
E         +                         "description": "",
E         +                         "content": {
E         +                             "application/json": {
E         +                                 "schema": {
E         +                                     "type": "array",
E         +                                     "items": {
E         +                                         "$ref": "#/components/schemas/User"
E         +                                     }
E         +                                 }
E         +                             }
E         +                         }
E         +                     }
E         +                 }
E                       }
```

**Comment by tomchristie** [comment]
I guess it must be something like we're doing a `issubclass` check on something, that's returning differently with the changes to metaclasses.

**Comment by alkovpro** [comment]
I solved this in PR #612

**Comment by d0ugal** [comment]
Yeah, #612 looks good.

**Pull request closed without merging**
