### PR TITLE
API Docs

### PR DESCRIPTION
**Pull request by tomchristie**
Work in progress.

image

### CODE REVIEW

**Comment by GomZik** [comment]
Hooray! Tom, please, take a look at how schema generates for Includes. Looks like Include path not used for paths key in schema.

**Comment by GomZik** [comment]
Also, swagger ui trying to OPTIONS before POST. Can we have autogenerated OPTIONS method?

**Comment by tomchristie** [comment]
screen shot 2018-05-08 at 12 55 39

**Comment by tomchristie** [comment]
> take a look at how schema generates for Includes. Looks like Include path not used for paths key in schema.

Yup, resolved in this PR.

**Comment by tomchristie** [comment]
Note that the API docs are not currently interactive.
We'll tackle that as an incremental improvement.

**Pull request merged**
