### PR TITLE
Fix PyPy on Travis

### PR DESCRIPTION
**Pull request by necaris**
Since `mypy`'s dependencies don't play well with PyPy, ensure they're not installed (and `mypy` itself is skipped) when running in that environment.

### CODE REVIEW

**Comment by necaris** [comment]
@tomchristie please let me know if this isn't the right place to submit this PR to and I'll move it appropriately!

**Comment by necaris** [comment]
Note: just rebased this onto `level-up` for maximal clarity

**Comment by tomchristie** [comment]
Thanks. pypy3.5 is now in the test matrix in #400

**Comment by tomchristie** [comment]
You’re welcome to either make a pull request introducing it back into the ‘level-up’ branch, or make a pull request once 0.4 goes live. Tho there may also be mypy issues that need clearing up before it could get merged.

**Comment by necaris** [comment]
@tomchristie thank you! Pushed https://github.com/encode/apistar/pull/421 to capture this.

**Pull request closed without merging**
