### PR TITLE
Pass `definitions` and `allow_coerce` for types.Type

### PR DESCRIPTION
**Pull request by asduj**

### CODE REVIEW

**Comment by tomchristie** [comment]
Looks right to me, yup.

For context could you give an example of when this is required and what currently fails without this change?

**Comment by asduj** [comment]
Pylint failed with error which not related to this PR
```
apistar/server/handlers.py:3:1: F401 'apistar.compat.pygments_css' imported but unused
```

**Comment by shvechikov** [comment]
I have faced into the same issue. Why this one is not merged?

**Comment by simon-mo** [comment]
bump. Can this be merged please? @tomchristie

**Comment by tomchristie** [comment]
Thanks - now redundant, given https://github.com/encode/apistar/pull/649

**Pull request closed without merging**
