### PR TITLE
None or '' raise Attribut Error : object has no attribute iso format

### PR DESCRIPTION
**Pull request by jgirardet**

### CODE REVIEW

**Comment by audiolion** [comment]
I feel like `to_string()` should return `''` instead of `None`

**Comment by jgirardet** [comment]
Make sens :stuck_out_tongue:

**Comment by tomchristie** [comment]
More generally what we want to make sure is that `DateTimeValidator` etc... properly support `allow_null`. I think we probably *should* serialize unset date/times as `None` rather than ''. Not sure if that implies we should rename `to_string`, since the `None` case is always going to be there for nullable validators.

**Comment by jgirardet** [comment]
to_string is meaningful.
to_serializable is not very nice ;-)
Not a problem if It's said in the doc that null date is None

**Comment by tomchristie** [comment]
Thanks folks! Closed via https://github.com/encode/apistar/commit/e8f60f6104e0ad49cf365d0b5941ad15c737128c
Note that `Type` handles the `None` cases so we don't need to deal with it in each Validator.

**Pull request closed without merging**
