### PR TITLE
(feat) JWT Authorization Component

### PR DESCRIPTION
**Pull request by audiolion**
Hi Tom!

As a follow up from #78 I implemented a JWT Component as part of a new file under the components module called "authorization.py" (to hold common auth components, OAUTH 1.0, OAUTH 2.0, Basic Auth, Digest Auth, AWS Signature, .. sky's the limit).

I tried to follow your current architecture patterns as best I could.

I wasn't sure if I should be including messages about why the request failed when injecting the JWT token / decoding it.

This is just a first pass and doesn't include the other half (creating a new JWT from a payload). Not hard to add but I wanted to make sure I was on the right track. Also wasn't sure how to name it, you have two components, the DecodedJWT and the EncodedJWT, maybe I should change them to that, but, `my_func(request: http.Request, token: authorization.DecodedJWT)` seems worse than just `authorization.JWT`.

The other question I had was about returning the Component, I put the payload inside the Component as `payload`, which requires `token.payload['key']` to get at the data, there is no other information with the JWT (I don't know why we would include the secret or the algorithm used) so I wasn't sure if I should just return a `typing.Dict[str, typing.Any]` "json" dict, but I felt that broke the idea that we are injecting a component called JWT  but is in fact just an anonymous object.

One last thing, I didn't see any use for adding an `Authorization` interface to `interfaces.py`, there were no methods on the JWT class that I would use. But now that I think of it, I could add a `decode` and `encode` method and refactor the JWT component to handle both cases, the only issue being how to call two different init methods on the same component.

edit: Latest commit included DecodedJWT/EncodedJWT Components, one is an http method to be injected and the other is a component to be imported and used. Only hangup I have with the imported component is that mypy will fail unless the person passing the payload argument to EncodedJWT wraps it in the `JSON` type. Not sure if that is what we want or not. My latest commit removes it.

### CODE REVIEW

**Comment by tomchristie** [comment]
Good stuff. We're at the point where we ought to start pushing towards third party packages rather functionality within core. I expect the Django ORM and SQLAlchemy backends will get pushed out to third party pckages two.

We're also currently missing a generic authentication API similar to what we have in REST framework. I should be addressing this fairly shortly.

**Comment by audiolion** [comment]
ok so break this out into a third-party package?

**Comment by tomchristie** [comment]
> ok so break this out into a third-party package?

That'll certainly be one aspect, yup.

Secondly, be prepared to do a bit of rejigging once a proper auth interface lands.

**Comment by audiolion** [comment]
haha alright 👍 ill close this then

**Pull request closed without merging**
