### PR TITLE
Improve schema command

### PR DESCRIPTION
**Pull request by bikeshedder**
- Fix JSON output of schema command
- Improve error handling for unsupported schema formats

### CODE REVIEW

**Comment by tomchristie** [comment]
The improved error handling is clear to me, we should def. have that, yup!
Not obvious at first what exact behavioral change "fix JSON output" relates to?
There's a linter error and a couple of test failures that you'd need to look into.
Optionally you could submit these two separate issues in separate pull requests,
which'd make it easier for us to start to pull in at least some of the work.

**Comment by bikeshedder** [comment]
The problem with returning a bytestring is that it outputs `b'...'` on the command line. This makes it impossible to use it to extract the schema like that:

    `$ apistar schema > api-schema.json`

I especially stumbled across this as I wanted to get pretty printing using `jq`:

   `$ apistar schema | jq`

I forgot to update the tests which should test for unicode strings.

**Comment by bikeshedder** [comment]
I just fixed the linting errors and tests. You're right that I could split this into two PRs but as both touch the same file with two adjacent lines I wanted to keep it simpler to merge them.

**Comment by tomchristie** [comment]
Fab, thanks!

**Pull request merged**
